services:
  bot:
    image: ghcr.io/itsamirhn/dongetobede:${BOT_VERSION:-latest}
    command: serve
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "8888:80"
    environment:
      - DONG_DB_URI=mongodb://mongodb:27017
      - DONG_BOT_LISTEN_PORT=80
      - DONG_BOT_TOKEN=${BOT_TOKEN}
      - DONG_BOT_ENDPOINT=dongetobede.amirhn.com

  mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: {}
