version: "3.9"

# Run this manifest on the staging server, so that the staging bot can use it

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: {}

networks:
  dong_default:
    external: true