package pkg

import (
	"crypto/sha1"

	"github.com/google/uuid"
)

// GenerateUUIDBasedOnString generated by ChatGPT
func GenerateUUIDBasedOnString(input string) uuid.UUID {
	// Convert the input string to a byte slice
	inputBytes := []byte(input)

	// Compute the SHA-1 hash of the input byte slice
	hash := sha1.Sum(inputBytes)

	// Use the hash as input to the uuid.NewSHA1() function
	return uuid.NewSHA1(uuid.NameSpaceOID, hash[:])
}
